# Generated by Django 5.0.4 on 2024-04-16 11:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bakery_address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bakery_address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Costs_by_month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_name', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('amount_of_costs', models.DecimalField(decimal_places=2, max_digits=8)),
                ('bakery_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytic_app.bakery_address')),
            ],
        ),
        migrations.CreateModel(
            name='Profitability_by_product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('quantity', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('total_sum', models.DecimalField(decimal_places=2, max_digits=8)),
                ('bakery_address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='analytic_app.bakery_address')),
            ],
        ),
    ]
